In [2]:
import numpy as np

In [21]:
# X= np.array([[1, 2], [4, 5], [6, 2]])
X= np.array([[4, 5]])
W = np.array([[1], [2]])

print(W.dot(X))

[[ 4  5]
 [ 8 10]]


In [ ]:
#SVM loss
# x = [1,]
def svm(x, y, W):
    scores = W.dot(x)
    scores = np.max(0, scores - scores[y] +1)
    scores[y] = 0

    return np.sum(scores)

In [ ]:
sum_col = np.sum(exp_x, axis=1).reshape(x.shape[0], 1)

In [31]:
#softmax stable for multidiim
def softmax_stable(x):
    if x.ndim >= 2:
        max_col = np.max(x, axis=1).reshape(x.shape[0], 1)
        sub_x = x - max_col

        exp_x = np.exp(sub_x)
        sum_col = np.sum(exp_x, axis=1).reshape(x.shape[0], 1)

        return exp_x / sum_col
    x = x - max(x)
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x1 = np.array([[5, 4, 2], [4, 2, 8], [4, 4, 1]])
x2 = np.array([5, 4, 2])
print(softmax_stable(x1))
print(softmax_stable(x2))

print(np.max(x1, axis=1).reshape(x1.shape[0], 1))
print(np.max(x1, axis=1))



[[0.70538451 0.25949646 0.03511903]
 [0.01794253 0.00242826 0.97962921]
 [0.48785555 0.48785555 0.0242889 ]]
[0.70538451 0.25949646 0.03511903]
[[5]
 [8]
 [4]]
[5 8 4]


In [33]:
a = np.array([[1, 2, 3]])

prob_dist = np.array([1, 2, 3], [4, 5, 6], [7, 8, 9])
print(prob_dist[a])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [32]:
#cross entrophy of X
def cross_entrophy(x, y, w):
    score = np.dot(w, x)
    prob_dist = softmax_stable(score)

    y.reshape(1, w.shape[0])

    loss_col = prob_dist[y]

    print(loss_col)


In [28]:
def softmax2(x):
    if x.ndim >= 2:
        exp_x = np.exp(x)
        sum_col = np.sum(exp_x, axis=1).reshape(x.shape[0], 1)
        print(sum_col)
        return exp_x / sum_col
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x1 = np.array([[5, 4, 2], [4, 2, 8], [4, 4, 1]])
x2 = np.array([5, 4, 2])
print(softmax1(x1))
print(softmax2(x1))
print(softmax(x2))

[ 210.40036523 3042.94519317  111.91458189]
[[7.05384513e-01 1.79425348e-02 6.60240692e-02]
 [2.59496460e-01 2.42825803e-03 2.66360106e+01]
 [2.59496460e-01 1.79425348e-02 2.42888977e-02]]
[[ 210.40036523]
 [3042.94519317]
 [ 111.91458189]]
[[0.70538451 0.25949646 0.03511903]
 [0.01794253 0.00242826 0.97962921]
 [0.48785555 0.48785555 0.0242889 ]]
[0.70538451 0.25949646 0.03511903]


------------------------------------------------------------------------------------------------------------------------------------------------
former

In [20]:
def softmax(x):  #it should work for single array and multiple arrays # mini batch version
  exp_x = np.exp(x)
  col_sum = np.sum(exp_x, axis=1).reshape(len(x), 1)
  output = exp_x/col_sum

  return output


In [21]:
x = np.array([[2, 3, 4]])

print(softmax(x))

[[0.09003057 0.24472847 0.66524096]]


In [3]:
#나의 방법
def softmax_1(x):  #it should work for single array and multiple arrays # mini batch version
  if x.ndim == 2:
    exp_x = np.exp(x)
    col_sum = np.sum(exp_x, axis=1).reshape(len(x), 1)
    output = exp_x/col_sum

    return output

  else:
    x = x - np.max(x)
    return np.exp(x)/np.sum(np.exp(x))


x1 = np.array([0.3, 2.9, 4.0])
x2 = np.array([1010, 1000, 990])
print(softmax_1(x1), softmax_1(x2))


[0.01821127 0.24519181 0.73659691] [9.99954600e-01 4.53978686e-05 2.06106005e-09]
